spring:
  application.name: addresses
  datasource:
    url: jdbc:h2:mem:addressdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    h2.console.enabled: true

server.port: 8085

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  #  endpoints.web.exposure.include: '*'
  tracing:
    sampling.probability: 1.0
  #    propagation.type: w3c
  #    enabled: true
  #    baggage.enabled: true
  #  metrics:
  #    distribution.percentiles-histogram.http.server.requests: true
  zipkin.tracing.endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}